; Загрузка больших архивных документов и книг
upload_max_filesize = 512M
post_max_size = 512M
memory_limit = 512M
max_execution_time = 300

; Symfony в dev
opcache.enable = 1
opcache.enable_cli = 0
opcache.validate_timestamps = 1
opcache.revalidate_freq = 0

; Сессии — через Redis (настроим в Symfony отдельно)
session.cookie_httponly = 1
session.cookie_samesite = "Lax"
session.use_strict_mode = 1

; Дата
date.timezone = Europe/Moscow
